**IMPORT NUMPY IN PYTHON**

In [3]:
import numpy as np

***Numpy Array Creation***

In [4]:
list1 = [2, 3, 6, 8]
array1 = np.array(list1)
print(array1)

[2 3 6 8]


In [5]:
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


***Creating a 2D-Numpy array***

In [8]:
array2=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8]])
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


***Creating a 3D-Numpy array***

In [10]:
array3=np.array([[[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]],
                 [[13, 14, 15, 16],
                  [17, 18, 19, 20],
                  [21, 22, 23, 24]]])
print(array3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


***Check Data Type of a Numpy Array***

In [11]:
array1 = np.array([1, 2, 3, 4])

print(array1.dtype)

int64


***Check dimensions of an Numpy Array***

In [13]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


***Check the size of an Array***

In [14]:
print(array1.size)
print(array2.size)
print(array3.size)

4
8
24


***Numpy Array shape attribute***

In [15]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(array1.shape)

(2, 3)


***Numpy Array itemsize attribute***

In [16]:
array1 = np.array([6, 7, 8, 9, 14])
array2 = np.array([2, 3, 4, 5, 10], dtype=np.int32)

print(array1.itemsize)
print(array2.itemsize)

8
4


***Numpy  Array data attribute***

In [18]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

print("\nData of array1 is: ",array1.data)
print("\nData of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7d7b4d36d9c0>

Data of array2 is:  <memory at 0x7d7b4d36d9c0>


***Access Array Elements Using Index***

In [22]:
print(array1[-1])
print(array2[1])


4
6
